pipeline{
    agent {
       label "aws-jenkins-slave"
    }
    stages{
        stage('Frontend-Deployment') {
            agent{
                    docker{
                            // Pull the Docker image
                        image 'dhruvbardolia/node-aws-terraform:v4'
                        args '-u root'
                    }
                }
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh '''#!/bin/bash
                        echo "Frontend Build..."

                        export NAME=${NAME}
                        export DIR=$(pwd)
                        git clone https://${USERNAME}:${PASSWORD}@github.com/TrainingAmigo/woliba-infra.git
                        cd woliba-infra/terraform/EC2-S3
                        envsubst < s3-bucket.conf | cat - > test.conf
                        cat test.conf > s3-bucket.conf
                        terraform init -backend-config=s3-bucket.conf
                        export S3_NAME=$(terraform output -raw s3_name)
                        export BACKEND_PUBLIC_IP=$(terraform output -raw public_ip)

                        #export API_URL=http://${NAME}-api.trainingamigo.com
                        export API_URL=http://$BACKEND_PUBLIC_IP
                        cd ../../..
                        cd $DIR
                        git clone https://${USERNAME}:${PASSWORD}@github.com/TrainingAmigo/react.git
                        cd react
                        #Checkout the branch based on a parameter
                        git checkout ${FE_BRANCH_NAME}
                        
                        # Append to the .env file
                        #echo "API_URL=http://1.2.3.4" >> .env.development
                        envsubst < .env | cat - > .env.test
                        cat .env.test > .env
                        #echo "API_URL=http://${BACKEND_PUBLIC_IP}" >> .env
                        cat .env
                        
                        # Install project dependencs3-bucket.confies and build
                        npm  config set unsafe-perm true
                        npm install
                        npm run build:test
                        echo "Frontend Build successfully..."

                        echo "Copying all the artifacts to S3 bucket..."
                        # S3 bucket name
                        aws s3 cp output/dist/ s3://${S3_NAME} --recursive
                        aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                        aws s3 cp public/ s3://${S3_NAME}/public --recursive
                        aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                        echo "Copied all the artifacts to S3 bucket..."

                        cd ..
                        cd $DIR
                        cd woliba-infra/terraform/EC2-S3
                        export S3_URL=$(terraform output -raw s3_url)
                        cd ..
                        cd RDS
                        envsubst < s3-bucket.conf | cat - > test.conf
                        cat test.conf > s3-bucket.conf
                        terraform init -backend-config=s3-bucket.conf
                        export RDS_NAME=$(terraform output -raw rds_name)
                        echo $RDS_NAME
                        export ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier $RDS_NAME --query "*[].[Endpoint.Address]" | grep '"' | cut -d '"' -f 2)
                        echo "Frontend URL : $S3_URL"
                        echo "RDS Endpoint : $ENDPOINT"
                        echo "Backend Public IP : $BACKEND_PUBLIC_IP"
                        cd ../../..
                        cd $DIR
                        rm -rf woliba-infra react
                        rm -rf *
                        echo "Frontend Deployment successfull..."
                    '''
                }
            }
        }
    }
    post {
        always { 
            cleanWs()
        }
    }
}
