pipeline{
    agent {
       label "aws-jenkins-slave"
    }
    stages{
        stage('Database Creation') {
            steps {
                script {
                    if (params.RDS_ENDPOINT == 'Production') {
                        withCredentials([
                            usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'), # Github credentials from Jenkins Credentials
                            usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'DB_PASSWORD', usernameVariable: 'DB_USERNAME'), # RDS credentials from Jenkins Credentials
                            string(credentialsId: 'USER_PASSWORD', variable: 'USER_PASSWORD'),
                            ]) {
                            echo "Database Creation"
                            sh '''#!/bin/bash
                                echo "RDS Creation..."
                                git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/dhruv-infra.git
                                cd dhruv-infra/terraform/RDS
                                export NAME=${NAME}
                                export bucket=terraform-backend-dhruv
                                export region=us-east-1 # Region for your infrastructure
                                envsubst < backend.conf | cat - > test.conf
                                cat test.conf > backend.conf
                                terraform init -backend-config=backend.conf
                                terraform fmt -check
                                terraform plan -input=false -var-file staging.tfvars -out ${NAME}.tfplan -lock=false -var="name=${NAME}"
                                terraform apply -input=false -lock=false "${NAME}.tfplan"
                                export RDS_NAME=$(terraform output -raw rds_name)
                                export ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier $RDS_NAME --region us-east-1 --query "*[].[Endpoint.Address]" | grep '"' | cut -d '"' -f 2)
                                echo $RDS_NAME
                                echo $ENDPOINT
                                sleep 15
                                mysql -h $ENDPOINT -u ${DB_USERNAME} -p${DB_PASSWORD} -D dhruvbardolia -e "USE dhruvbardolia; UPDATE users SET mail = CONCAT('dhruv-user-', uid, '@dhruv.io') where mail != 'superteam@dhruv.io';"
                                mysql -h $ENDPOINT -u ${DB_USERNAME} -p${DB_PASSWORD} -D dhruvbardolia -e "USE dhruvbardolia; UPDATE users SET password = '${USER_PASSWORD}';"
                                echo "RDS Creation successfull..."
                            '''
                        }
                    } 
                    else {
                        withCredentials([
                            usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'),
                            usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'DB_PASSWORD', usernameVariable: 'DB_USERNAME'),
                            string(credentialsId: 'USER_PASSWORD', variable: 'USER_PASSWORD'),
                            ]) {
                            echo "RDS-DEV-DB"
                            sh '''#!/bin/bash
                                echo "Fetching the RDS..."
                                git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/dhruv-infra.git
                                export ENDPOINT="dhruvbardolia-dev.c5ag8ujkoc4k.us-east-1.rds.amazonaws.com"
                                echo $ENDPOINT
                                sleep 15
                                mysql -h $ENDPOINT -u ${DB_USERNAME} -p${DB_PASSWORD} -e "SHOW DATABASES;"
                                echo "RDS Connection is success..."
                            '''
                        }
                    }
                }
            }
        }
        stage('Backend-Deployment-with-s3') {
            steps {
                script {
                    if (params.RDS_ENDPOINT == 'Production') {
                        withCredentials([
                            usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'),
                            usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'DB_dhruvbardolia_PASSWORD', usernameVariable: 'DB_dhruvbardolia_USERNAME'),
                            string(credentialsId: 'APP_KEY', variable: 'APP_KEY'),
                            string(credentialsId: 'DB_HOST', variable: 'DB_HOST'),
                            string(credentialsId: 'SPARKPOST_SECRET', variable: 'SPARKPOST_SECRET'),
                            string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                            string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'BUGSNAG_API_KEY', variable: 'BUGSNAG_API_KEY'),
                            string(credentialsId: 'FCM_SERVER_KEY', variable: 'FCM_SERVER_KEY'),
                            string(credentialsId: 'STRIPE_KEY', variable: 'STRIPE_KEY'),
                            string(credentialsId: 'BUGSNAG_API_KEY', variable: 'BUGSNAG_API_KEY'),
                            string(credentialsId: 'STRIPE_SECRET', variable: 'STRIPE_SECRET'),
                            
                            ]) {
                            echo "Backend-Deployment starts..."
                            sh '''#!/bin/bash

                                echo "Packer building new AMI..."
                                git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/dhruv-infra.git
                                export DIR=$(pwd)
                                cd dhruv-infra/terraform/RDS
                                envsubst < s3-bucket.conf | cat - > test.conf
                                cat test.conf > s3-bucket.conf
                                terraform init -backend-config=s3-bucket.conf
                                export RDS_NAME=$(terraform output -raw rds_name)
                                echo $RDS_NAME
                                export ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier $RDS_NAME --region us-east-1 --query "*[].[Endpoint.Address]" | grep '"' | cut -d '"' -f 2)
                                echo "RDS-Endpoint: $ENDPOINT"
                                cd ../../..
                                cd $DIR
                                cd dhruv-infra/packer
                                packer init .
                                packer build -var "AMI_NAME=${NAME}" -var "BE_BRANCH_NAME=${BE_BRANCH_NAME}" -var "APP_KEY=${APP_KEY}" -var "APP_URL=http://localhost" -var "DB_HOST=$ENDPOINT" -var "DB_NAME=dhruvbardolia" -var "DB_USERNAME=${DB_dhruvbardolia_USERNAME}" -var "DB_PASSWORD=${DB_dhruvbardolia_PASSWORD}" -var "SPARKPOST_SECRET=${SPARKPOST_SECRET}" -var "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var "BUGSNAG_API_KEY=${BUGSNAG_API_KEY}" -var "FCM_SERVER_KEY=${FCM_SERVER_KEY}" -var "STRIPE_KEY=${STRIPE_KEY}" -var "STRIPE_SECRET=${STRIPE_SECRET}" build.pkr.hcl
                                AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
                                echo "New AMI is created: $AMI_ID"

                                echo "Backend Deployment..."
                                cd ..
                                cd terraform/EC2-S3
                                envsubst < s3-bucket.conf | cat - > test.conf
                                cat test.conf > s3-bucket.conf
                                terraform init -backend-config=s3-bucket.conf
                                terraform fmt -check
                                terraform plan -input=false -var-file staging.tfvars -out ${NAME}.tfplan -lock=false -var="name=${NAME}" -var="image_id=$AMI_ID"
                                terraform apply -input=false -lock=false "${NAME}.tfplan"
                                echo "Backend Public ip address is $BACKEND_PUBLIC_IP"
                                echo "Backend Deployment successfull..."
                            '''
                        }
                    }
                    else {
                        withCredentials([
                            usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'),
                            usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'DB_dhruvbardolia_PASSWORD', usernameVariable: 'DB_dhruvbardolia_USERNAME'),
                            string(credentialsId: 'APP_KEY', variable: 'APP_KEY'),
                            string(credentialsId: 'DB_HOST', variable: 'DB_HOST'),
                            string(credentialsId: 'SPARKPOST_SECRET', variable: 'SPARKPOST_SECRET'),
                            string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                            string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'BUGSNAG_API_KEY', variable: 'BUGSNAG_API_KEY'),
                            string(credentialsId: 'FCM_SERVER_KEY', variable: 'FCM_SERVER_KEY'),
                            string(credentialsId: 'STRIPE_KEY', variable: 'STRIPE_KEY'),
                            string(credentialsId: 'BUGSNAG_API_KEY', variable: 'BUGSNAG_API_KEY'),
                            string(credentialsId: 'STRIPE_SECRET', variable: 'STRIPE_SECRET'),
                            
                            ]) {
                            echo "Backend-Deployment starts..."
                            sh '''#!/bin/bash

                                echo "Packer building new AMI..."
                                git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/dhruv-infra.git
                                export DIR=$(pwd)
                                export ENDPOINT="dhruvbardolia-dev.c5ag8ujkoc4k.us-east-1.rds.amazonaws.com"
                                echo "RDS-Endpoint: $ENDPOINT"
                                cd $DIR
                                cd dhruv-infra/packer
                                packer init .
                                packer build -var "AMI_NAME=${NAME}" -var "BE_BRANCH_NAME=${BE_BRANCH_NAME}" -var "APP_KEY=${APP_KEY}" -var "APP_URL=http://localhost" -var "DB_HOST=$ENDPOINT" -var "DB_NAME=dhruvbardolia" -var "DB_USERNAME=${DB_dhruvbardolia_USERNAME}" -var "DB_PASSWORD=${DB_dhruvbardolia_PASSWORD}" -var "SPARKPOST_SECRET=${SPARKPOST_SECRET}" -var "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var "BUGSNAG_API_KEY=${BUGSNAG_API_KEY}" -var "FCM_SERVER_KEY=${FCM_SERVER_KEY}" -var "STRIPE_KEY=${STRIPE_KEY}" -var "STRIPE_SECRET=${STRIPE_SECRET}" build.pkr.hcl
                                AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
                                echo "New AMI is created: $AMI_ID"

                                echo "Backend Deployment..."
                                cd ..
                                cd terraform/EC2-S3
                                envsubst < s3-bucket.conf | cat - > test.conf
                                cat test.conf > s3-bucket.conf
                                terraform init -backend-config=s3-bucket.conf
                                terraform fmt -check
                                terraform plan -input=false -var-file staging.tfvars -out ${NAME}.tfplan -lock=false -var="name=${NAME}" -var="image_id=$AMI_ID"
                                terraform apply -input=false -lock=false "${NAME}.tfplan"
                                echo "Backend Public ip address is $BACKEND_PUBLIC_IP"
                                echo "Backend Deployment successfull..."
                            '''
                        }
                    }
                }
            }
        }
        stage('Frontend-Deployment') {
            agent{
                    docker{
                            // Pull the Docker image
                        image 'dhruvbardolia/node-aws-terraform:v4'
                        args '-u root'
                    }
                }
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh '''#!/bin/bash
                        echo "Frontend Build..."

                        export NAME=${NAME}
                        export DIR=$(pwd)
                        git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/dhruv-infra.git
                        cd dhruv-infra/terraform/EC2-S3
                        envsubst < s3-bucket.conf | cat - > test.conf
                        cat test.conf > s3-bucket.conf
                        terraform init -backend-config=s3-bucket.conf
                        export S3_NAME=$(terraform output -raw s3_name)
                        export BACKEND_PUBLIC_IP=$(terraform output -raw public_ip)

                        export API_URL=http://$BACKEND_PUBLIC_IP
                        cd $DIR
                        git clone https://${USERNAME}:${PASSWORD}@github.com/dhruvbardolia/react.git
                        cd react
                        #Checkout the branch based on a parameter
                        git checkout ${FE_BRANCH_NAME}
                        
                        # Append to the .env file
                        envsubst < .env | cat - > .env.test
                        cat .env.test > .env
                        cat .env
                        
                        # Install project dependencs3-bucket.confies and build
                        npm  config set unsafe-perm true
                        npm install
                        npm run build:test
                        echo "Frontend Build successfully..."

                        echo "Copying all the artifacts to S3 bucket..."
                        # S3 bucket name
                        aws s3 cp output/dist/ s3://${S3_NAME} --recursive
                        aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                        aws s3 cp public/ s3://${S3_NAME}/public --recursive
                        aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                        echo "Copied all the artifacts to S3 bucket..."

                        cd ..
                        cd $DIR
                        cd dhruv-infra/terraform/EC2-S3
                        export S3_URL=$(terraform output -raw s3_url)
                        cd ..
                        echo "Frontend URL : $S3_URL"
                        echo "RDS Endpoint : $ENDPOINT"
                        echo "Backend Public IP : $BACKEND_PUBLIC_IP"
                        cd ../../..
                        cd $DIR
                        rm -rf dhruv-infra react
                        rm -rf *
                        echo "Frontend Deployment successfull..."
                    '''
                }
            }
        }
        // stage('Register Job in S3') {
        //     steps {
        //         script {
        //             echo "S3 Registering..."
        //             def jobName = NAME
        //             def s3Bucket = "live-env.dhruv.io"
        //             def fileName = "index.html"
        //             def tempFile = "temp.txt"

        //             withCredentials([
        //                 string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
        //                 string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
        //             ]) {
        //                 sh "aws s3 cp s3://${s3Bucket}/${fileName} ${tempFile} || touch ${tempFile}"
        //                 sh "echo ${jobName} >> ${tempFile}"
        //                 sh "aws s3 cp ${tempFile} s3://${s3Bucket}/${fileName}"
        //                 sh "rm ${tempFile}"
        //             }
        //             echo "S3 Registration is completed"
        //             echo "http://live-env.dhruv.io/"
        //         }
        //     }
        // }
        stage('Store Environment Name in DynamoDB') {
            steps {
                script {
                    def environmentName = env.NAME

                    withCredentials([
                        string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        sh "aws dynamodb put-item --table-name environments --region us-east-1 --item '{\"Name\": {\"S\": \"${environmentName}\"}}'"
                    }
                    echo "Stored environment name '${environmentName}' in DynamoDB."
                }
            }
        }
    }
    post {
        always { 
            cleanWs()
        }
    }
}