pipeline{
    agent {
       label "aws-jenkins-slave"
    }
    stages{
        stage('RDS-DB-deletion') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'),
                    usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')
                    ]) {
                    echo "RDS-DB-Creation"
                    sh '''#!/bin/bash
                        echo "RDS Deletion..."
                        git clone https://${USERNAME}:${PASSWORD}@github.com/TrainingAmigo/woliba-infra.git
                        cd woliba-infra/terraform/RDS
                        envsubst < s3-bucket.conf | cat - > test.conf
                        cat test.conf > s3-bucket.conf
                        terraform init -backend-config=s3-bucket.conf
                        terraform fmt -check
                        terraform destroy -input=false -var-file staging.tfvars -var "name=${NAME}" -auto-approve
                        echo "RDS Deleted successfully..."
                    '''
                }
            }
        }
        stage('Backend-deletion') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh '''#!/bin/bash
                        echo "Deleting environment..."

                        echo "De-registring AMI..."
                        AMI_ID=$(aws ec2 describe-images --region us-east-1 --filters Name=name,Values=${NAME} | jq '.Images[0].ImageId' | sed 's/"//g')
                        SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query 'Images[0].BlockDeviceMappings[0].Ebs.SnapshotId' --output text --region us-east-1)
                        aws ec2 deregister-image --image-id $AMI_ID --region us-east-1
                        echo "AMI De-registered..."
                        echo "Deleting Snapshot..."
                        aws ec2 delete-snapshot --snapshot-id $SNAPSHOT_ID --region us-east-1
                        echo "Snapshot deleted..."
                        git clone https://${USERNAME}:${PASSWORD}@github.com/TrainingAmigo/woliba-infra.git
                        cd woliba-infra/terraform/EC2-S3
                        envsubst < s3-bucket.conf | cat - > test.conf
                        cat test.conf > s3-bucket.conf
                        terraform init -backend-config=s3-bucket.conf
                        terraform fmt -check
                        terraform destroy -input=false -var-file staging.tfvars -var "name=${NAME}" -var="image_id=${AMI_ID}" -auto-approve
                        echo "Environment Deleted successfully..."
                    '''
                }
            }
        }
        // stage('Remove Job from S3') {
        //     steps {
        //         script {
        //             echo "De-registering of the live environment from S3 Bucket is started..."

        //             def jobNameToRemove = NAME 
        //             def s3Bucket = "live-env.woliba.io"
        //             def fileName = "index.html"
        //             def tempFile = "temp.txt"

        //             withCredentials([
        //                 string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
        //                 string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
        //             ]) {
        //                 sh "aws s3 cp s3://${s3Bucket}/${fileName} ${tempFile}"
        //                 sh "sed -i '/${jobNameToRemove}/d' ${tempFile}"
        //                 sh "aws s3 cp ${tempFile} s3://${s3Bucket}/${fileName}"
        //                 sh "rm ${tempFile}"
        //             }
        //             echo "De-registering of the live environment from S3 Bucket is completed."
        //         }
        //     }
        // }
        stage('Remove Environment from DynamoDB') {
            steps {
                script {
                    def environmentName = env.NAME

                    withCredentials([
                        string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        sh "aws dynamodb delete-item --table-name environments --region us-east-1 --key '{\"Name\": {\"S\": \"${environmentName}\"}}'"
                    }
                    echo "Removed environment '${environmentName}' from DynamoDB."
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}