pipeline{
    agent {
       label "aws-jenkins-slave"
    }
    stages{
        stage('RDS-DB-deletion') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'rds-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME'),
                    usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')
                    ]) {
                    echo "RDS-DB-deletion"
                    sh '''#!/bin/bash
                        echo "RDS Deletion..."
                        cd terraform/RDS
                        envsubst < backend.conf | cat - > test.conf
                        cat test.conf > backend.conf
                        terraform init -backend-config=backend.conf
                        terraform fmt -check
                        terraform destroy -input=false -var-file staging.tfvars -var "name=${NAME}" -auto-approve
                        echo "RDS Deleted successfully..."
                    '''
                }
            }
        }
        stage('Backend-deletion') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh '''#!/bin/bash
                        echo "Deleting environment..."

                        echo "De-registring AMI..."
                        AMI_ID=$(aws ec2 describe-images --region us-east-1 --filters Name=name,Values=${NAME} | jq '.Images[0].ImageId' | sed 's/"//g')
                        SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query 'Images[0].BlockDeviceMappings[0].Ebs.SnapshotId' --output text --region us-east-1)
                        aws ec2 deregister-image --image-id $AMI_ID --region us-east-1
                        echo "AMI De-registered..."
                        echo "Deleting Snapshot..."
                        aws ec2 delete-snapshot --snapshot-id $SNAPSHOT_ID --region us-east-1
                        echo "Snapshot deleted..."
                        cd terraform/EC2-S3
                        envsubst < backend.conf | cat - > test.conf
                        cat test.conf > backend.conf
                        terraform init -backend-config=backend.conf
                        terraform fmt -check
                        terraform destroy -input=false -var-file staging.tfvars -var "name=${NAME}" -var="image_id=${AMI_ID}" -auto-approve
                        echo "Environment Deleted successfully..."
                    '''
                }
            }
        }
        stage('Remove Environment from DynamoDB') {
            steps {
                script {
                    def environmentName = env.NAME

                    withCredentials([
                        string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        sh "aws dynamodb delete-item --table-name environments --region us-east-1 --key '{\"Name\": {\"S\": \"${environmentName}\"}}'"
                    }
                    echo "Removed environment '${environmentName}' from DynamoDB."
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}