name                   = "example"
iam_profile            = "example-instance-profile"
image_id               = ""
instance_type          = "t3.medium"
key_name               = "example-key"
vpc_security_group_ids = ["sg-xxxxxxxxxxxxxxxxx"]
subnets                = ["subnet-aaaaaaaaaaaaaaaaa", "subnet-bbbbbbbbbbbbbbbb"]
route53_zone_id        = "ZXXXXXXXXXXXX"
root_domain            = "example.com"
frontend_bucket_suffix = "fe.example.com"
aws_region             = "us-east-1"
