pipeline {
    agent {
        label "aws-jenkins-slave"
    }
    environment {
        S3_NAME = 'dev.woliba.io'
    }
    stages {
        stage('Frontend-Deployment') {
            steps {
                script {
                    agent {
                        docker {
                            image 'milonipatel/aws-node-terraform:latest'
                            args '-u root'
                        }
                    }
                    steps {
                        withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                            sh '''#!/bin/bash
                                echo "Frontend Build..."
                                export API_URL=https://dev.api.trainingamigo.com
                                export DIR=$(pwd)
                                git clone https://${USERNAME}:${PASSWORD}@github.com/TrainingAmigo/react.git
                                cd react
                                #Checkout the branch based on a parameter
                                git checkout ${FE_BRANCH_NAME}
                                git pull
                                # Install project dependencies and build
                                envsubst < .env | cat - > .env.test
                                cat .env.test > .env
                                npm  config set unsafe-perm true
                                npm install
                                npm run build:dev
                                echo "Frontend Build successfully..."

                                echo "Copying all the artifacts to S3 bucket..."
                                # S3 bucket name
                                aws s3 cp output/dist/ s3://${S3_NAME} --recursive
                                aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                                aws s3 cp public/ s3://${S3_NAME}/public --recursive
                                aws s3 ls s3://${S3_NAME} --recursive --human-readable --summarize
                                echo "Copied all the artifacts to S3 bucket..."

                                cd ..
                                cd $DIR
                                rm -rf woliba-infra react
                                rm -rf *
                                echo "Frontend Deployment successfull..."
                            '''
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
